# Generated by Django 4.1 on 2022-09-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='branch_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
