# Generated by Django 4.1 on 2022-08-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEmpleado',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.TextField(max_length=255, verbose_name='Ciudad')),
                ('provincia', models.TextField(max_length=255, verbose_name='Provincia')),
                ('pais', models.TextField(max_length=255, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Dirección del empleado',
                'verbose_name_plural': 'Direcciones del empleado',
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField(max_length=255, verbose_name='Nombre')),
                ('employee_surname', models.TextField(max_length=255, verbose_name='Apellido')),
                ('employee_hire_date', models.TextField(verbose_name='Fecha de contratación')),
                ('employee_dni', models.TextField(db_column='employee_DNI', max_length=8, verbose_name='DNI')),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'managed': False,
            },
        ),
    ]
