# Generated by Django 4.0.6 on 2022-09-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeCuentas',
            fields=[
                ('tipos_de_cuentas_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_cuenta', models.TextField(max_length=30, verbose_name='Tipo de cuenta')),
            ],
            options={
                'verbose_name': 'Tipo de cuenta',
                'db_table': 'tipo_de_cuentas',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('tipos_de_cuentas_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.tiposdecuentas')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'cuenta',
            },
        ),
    ]
