# Generated by Django 4.1 on 2022-08-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDeCuentas',
            fields=[
                ('tipos_de_cuentas_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_cuenta', models.TextField(max_length=30, verbose_name='Tipo de cuenta')),
            ],
            options={
                'verbose_name': 'Tipo de cuenta',
                'db_table': 'tipos_de_cuentas',
                'managed': False,
            },
        ),
    ]
