# Generated by Django 4.0.6 on 2022-09-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='customer_id',
        ),
    ]
