# Generated by Django 4.0.6 on 2022-09-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_dob'),
        ('cuentas', '0002_remove_cuenta_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='customer_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
