# Generated by Django 4.1 on 2022-08-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('customer_surname', models.CharField(max_length=255, verbose_name='Apellido')),
                ('customer_DNI', models.IntegerField(max_length=8, verbose_name='DNI')),
                ('dob', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.TextField(max_length=255, verbose_name='Ciudad')),
                ('provincia', models.TextField(max_length=255, verbose_name='Provincia')),
                ('pais', models.TextField(max_length=255, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Dirección del cliente',
                'verbose_name_plural': 'Direcciones del cliente',
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('tipo_cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipos_de_clientes', models.TextField(verbose_name='Tipo de cliente')),
            ],
            options={
                'verbose_name': 'Tipo de cliente',
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
    ]
