# Generated by Django 4.0.6 on 2022-09-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('customer_surname', models.CharField(max_length=255, verbose_name='Apellido')),
                ('customer_DNI', models.IntegerField(verbose_name='DNI')),
                ('dob', models.DateField(verbose_name='Fecha de nacimiento')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.authuser')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('tipo_cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipos_de_clientes', models.TextField(verbose_name='Tipo de cliente')),
            ],
            options={
                'verbose_name': 'Tipo de cliente',
                'db_table': 'tipo_cliente',
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.TextField(max_length=255, verbose_name='Ciudad')),
                ('provincia', models.TextField(max_length=255, verbose_name='Provincia')),
                ('pais', models.TextField(max_length=255, verbose_name='País')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Dirección del cliente',
                'verbose_name_plural': 'Direcciones del cliente',
                'db_table': 'direccion_cliente',
            },
        ),
    ]
