# Generated by Django 4.1 on 2022-09-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='direccioncliente',
            options={'verbose_name': 'Dirección del cliente', 'verbose_name_plural': 'Direcciones del cliente'},
        ),
        migrations.AlterModelOptions(
            name='tipocliente',
            options={'verbose_name': 'Tipo de cliente'},
        ),
    ]
