# Generated by Django 4.1 on 2022-09-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_dob'),
        ('clientes', '0003_alter_cliente_options_alter_direccioncliente_options_and_more'),
    ]

    operations = [
    ]
