# Generated by Django 4.1 on 2022-09-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_sucursal'),
        ('clientes', '0005_cliente_branch_id_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.sucursal'),
        ),
    ]
