# Generated by Django 4.1 on 2022-09-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='branch_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='empleados.sucursal'),
        ),
    ]
