# Generated by Django 4.1 on 2022-09-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_sucursal_branch_id'),
        ('clientes', '0004_alter_cliente_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.sucursal'),
        ),
    ]
