# Generated by Django 4.1 on 2022-09-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='branch_id',
            field=models.IntegerField(verbose_name='Sucursal'),
        ),
    ]
