# Generated by Django 4.1 on 2022-08-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.TextField(max_length=30, verbose_name='Tipo de préstamo')),
                ('loan_date', models.TextField(verbose_name='Fecha')),
                ('loan_total', models.IntegerField(verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
    ]
