# Generated by Django 4.0.6 on 2022-09-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamos_tabla',
        ),
    ]
